CREATE TABLE AE (
	A VARCHAR(256) PRIMARY KEY,
	E VARCHAR(256)
);

CREATE TABLE CA (
	C VARCHAR(256) PRIMARY KEY,
	A VARCHAR(256),
	FOREIGN KEY (A) REFERENCES AE (A)
);

CREATE TABLE CB (
	C VARCHAR(256),
	B VARCHAR(256),
	FOREIGN KEY (C) REFERENCES CA (C)
);

CREATE TABLE CD (
	C VARCHAR(256),
	D VARCHAR(256),
	FOREIGN KEY (C) REFERENCES CA (C)
);

INSERT INTO ae(a,e)SELECT t."A",t."E" FROM test t GROUP BY t."A",t."E";

INSERT INTO ca(c,a)SELECT t."C",t."A" FROM test t GROUP BY t."A",t."C";

INSERT INTO cb(c,b)SELECT t."C",t."B" FROM test t GROUP BY t."B",t."C";

INSERT INTO cd(c,d)SELECT t."C",t."D" FROM test t GROUP BY t."C",t."D";
