stack:
	g++ main_MyStack.cpp -o MyStack
	./MyStack
list:
	g++ main_LinkedList.cpp -o LinkedList
	./LinkedList
play:
	g++ main_Playlist.cpp Playlist.cpp Entry.cpp HistoryRecord.cpp -o Playlist
	./Playlist



